### ISSUE TITLE
点击提示的位置在if条件内容改为 if (typeof require === "undefined" || !require.cache)

### ISSUE THREAD

**Issue by songyipan** [vbenjs/vite-plugin-mock#109]
![image](https://github.com/vbenjs/vite-plugin-mock/assets/65063252/70660680-0b5b-4f53-9d4e-4d40d7430c8a)

将代码这样改:![image](https://github.com/vbenjs/vite-plugin-mock/assets/65063252/5f6097ab-d2bb-435f-a988-700025d4160a)
不然运行时会报：
![image](https://github.com/vbenjs/vite-plugin-mock/assets/65063252/e0abb7db-a8fe-4d0d-bfcf-e0c9201715b8)

**Comment by codepandy** [comment]
我也遇到了，但是发现github上最新的版本是2.9.1，安装2.9.1就行了

**Comment by wwhwwhwwh** [comment]
删除自己项目根目录下 `package.json` 中的 这一行

```json
"type": "module"
```

声明type:"module", 默认会读取 dist/index.mjs ，删除之后会读取  dist/index.cjs 

环境
```json
"vite": "^4.4.9",
"vite-plugin-mock": "^3.0.0"
"node":"v16.14.0"
```
