### ISSUE TITLE
手动创建 mock/user.ts 文件后项目异常

### ISSUE THREAD

**Issue by OHUHO** [vbenjs/vite-plugin-mock#115]
当我安装好 3.0.0 版本，配置了 vite.config.ts 后，随后根目录下创建了 mock 文件夹，并在该文件夹内创建了 user.ts 文件，随后就自动为我创建了下面的文件，整个过程是自动创建，然后又自动删除，让我怀疑这个插件是否完善
![image](https://github.com/vbenjs/vite-plugin-mock/assets/85296730/9c039a7d-f1a0-478e-9fd3-79455282437e)

**Comment by OHUHO** [comment]
文件内容是：//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFtdLAogICJzb3VyY2VzQ29udGVudCI6IFtdLAogICJtYXBwaW5ncyI6ICIiLAogICJuYW1lcyI6IFtdCn0K

**Comment by sky5454** [comment]
## 我的环境
vite + vite-plugin-mock + yarn
## 内容
插件好像不完善，修改mock的js/ts文件就很容易卡住，目前我是通过vite.config.ts里的vite配置禁用掉mock自动刷新功能
```ts
  viteMockServe({
      mockPath: 'mock',
      logger: true,
      watchFiles: false
    }),
```

但是代价就是每次修改mock之后都需要手动关掉再开启（如果不需要更新mock就不需要重开）
```
# 按q退出
q
# 重新编译
yarn dev
```

**Comment by condorheroblog** [comment]
见这个回答：https://github.com/vbenjs/vite-plugin-mock/issues/98#issuecomment-1782467433

@sky5454  禁用 watch 是目前最好的解决办法。

**Comment by sky5454** [comment]
> 见这个回答：[#98 (comment)](https://github.com/vbenjs/vite-plugin-mock/issues/98#issuecomment-1782467433)
> 
> @sky5454 禁用 watch 是目前最好的解决办法。

是的，我也察觉到是mjs的问题，其实临时文件生成不应该出现在源码目录，感觉是设计上的失误。
