### ISSUE TITLE
可以设置是否启用mock的开关吗？

### ISSUE THREAD

**Issue by zhoufanglu** [vbenjs/vite-plugin-mock#121]
我现在的需求是， 根据后端请求的接口字段，来判断是否需要启动Mock， 启用Mock是否能动态呢？

**Comment by condorheroblog** [comment]
不可以

你这个需求，最好的办法是通过控制请求的跟路径来解决：

1. `api/get-user-info`
2. `mock/get-user-info`

**Comment by zhoufanglu** [comment]
> 不可以
> 
> 你这个需求，最好的办法是通过控制请求的跟路径来解决：
> 
> 1. `api/get-user-info`
> 2. `mock/get-user-info`

感谢回答，最终在拦截器内解决了。。
