### ISSUE TITLE
是否支持vite5

### ISSUE THREAD

**Issue by wzs28150** [vbenjs/vite-plugin-mock#124]
再vite5中使用启动会有警告，开启VITE_CJS_TRACE=true后追踪到这个插件，请问该插件是否支持vite5?![image](https://github.com/vbenjs/vite-plugin-mock/assets/21290257/760e5771-a588-40b8-8abf-6831be9d4a9a)

**Comment by haiweilian** [comment]
最新 3.0.1 支持。你应该添加  "type": "module" 因为现有的插件基本都兼容 vite2-5 ，默认加载的都是 cjs。

这个警告解决方案详见：https://cn.vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

**Comment by wzs28150** [comment]
升级到3.0.1正常了 感谢~

**Comment by shaojiankui** [comment]
VueDevTools(),
No overload matches this call.
  The last overload gave the following error.
    Type 'Plugin<any>' is not assignable to type 'PluginOption'.
      Type 'import("/Users/jakey/Desktop/vue/node_modules/_vite@5.0.12@vite/dist/node/index").Plugin<any>' is not assignable to type 'import("/Users/jakey/Desktop/vue/node_modules/vite/dist/node/index").Plugin<any>'.
        Types of property 'apply' are incompatible.
          Type '"serve" | "build" | ((this: void, config: import("/Users/jakey/Desktop/vue/node_modules/_vite@5.0.12@vite/dist/node/index").UserConfig, env: import("/Users/jakey/Desktop

我为啥报这个
