### ISSUE TITLE
无法使用 vite 中 define 的信息

### ISSUE THREAD

**Issue by cnguu** [vbenjs/vite-plugin-mock#35]
`vite.config.ts`

```typescript
export default () => {
  return {
    define: { __APP_INFO__: "hello" }
  }
}
```

`mock/test.ts`

```typescript
console.log(__APP_INFO__)
// undefined

// 同样，获取 env 报错
console.log(import.meta.env.VITE_TEST)
// warning: "import.meta" is not available in the configured target environment ("es2015") and will be empty
```

**Comment by wanglei520** [comment]
关于如何解决这类问题的很简单，还是看了大佬的代码后才知道如何解决的
`viteMockServe({
    ignore: /^\_/,  // 注意这里配置了忽略自动读取的文件，以_下划线开头的文件
    mockPath: 'mock', // 如果文件中有index开头的直接读取，会去读取mock文件夹下的文件，如果文件_开头就不会读取
    localEnabled: !isBuild,
    prodEnabled: isBuild,
    injectCode: `
      import { setupProdMockServer } from '../mock/_index';  // 这里导入的文件就会自动读取

      setupProdMockServer();
      `
  })`
所以读取的文件要以_开头，也就是入口文件要以_开头

**Comment by wanglei520** [comment]
关于如何解决这类问题的很简单，还是看了大佬的代码后才知道如何解决的
`
viteMockServe({ ignore: /^\_/, // 注意这里配置了忽略自动读取的文件，以_下划线开头的文件 mockPath: 'mock', // 如果文件中有index开头的直接读取，会去读取mock文件夹下的文件，如果文件_开头就不会读取 localEnabled: !isBuild, prodEnabled: isBuild, injectCode:
import { setupProdMockServer } from '../mock/_index'; // 这里导入的文件就会自动读取
  setupProdMockServer();
})
`
所以读取的文件要以_开头，也就是入口文件要以_开头

**Comment by anncwb** [comment]
这个目前可能支持不了

**Comment by anncwb** [comment]
define内的可以做简单兼容，但是从环境变量设置的目前没办法做到
