### ISSUE TITLE
mock文件修改之后读取的还是缓存文件

### ISSUE THREAD

**Issue by wendyAndJken** [vbenjs/vite-plugin-mock#52]
![image](https://user-images.githubusercontent.com/34601508/138873393-48c341fc-ea26-47ea-8287-33bc4595996f.png)
Object.keys(__require.cache).forEach((file) => {
    if (file === absConfigPath || file.indexOf(absMockPath) > -1) {
      delete __require.cache[file];
    }
  });
 __require无法清除缓存，导致mock文件修改之后读取的还是缓存文件。
  __require替代为require后可正常使用。
这个是我打开方式不对，还是bug？

**Comment by anncwb** [comment]
可以尝试最新版
