### ISSUE TITLE
mock 数据中导入了 svg component 提示没有loader

### ISSUE THREAD

**Issue by cqh963852** [vbenjs/vite-plugin-mock#53]
![image](https://user-images.githubusercontent.com/17702287/139359539-c80b1f2e-b859-4de3-9884-e636558ef9c3.png)

**Comment by qybksbb** [comment]
i have the same problem

**Comment by anncwb** [comment]
目前只支持简单的mock数据，不支持这些类型，如果要支持，有太多的类型要做。

**Comment by qybksbb** [comment]
您发给我的邮件已收到。
 
谢谢！
 
宋蓓蓓
