### ISSUE TITLE
vite3 不生效

### ISSUE THREAD

**Issue by chenxi24** [vbenjs/vite-plugin-mock#80]
![image](https://user-images.githubusercontent.com/40349890/184871891-dedf43d1-033e-4546-afae-748b091e3b02.png)

**Comment by yulimchen** [comment]
> ![image](https://user-images.githubusercontent.com/40349890/184871891-dedf43d1-033e-4546-afae-748b091e3b02.png)

请求这个问题如何解决呢？vite4 同样有这个问题

**Comment by chenxi24** [comment]
You can try this https://github.com/vbenjs/vite-plugin-mock/issues/85#issuecomment-1286356791

**Comment by yulimchen** [comment]
> You can try this [#85 (comment)](https://github.com/vbenjs/vite-plugin-mock/issues/85#issuecomment-1286356791)

Thx~
