### ISSUE TITLE
线上环境get请求中query获取不到完整的数组参数，开发环境正常

### ISSUE THREAD

**Issue by Lin-Van** [vbenjs/vite-plugin-mock#93]
版本：最新版本
请求发送数组参数：{selectProps:["a", "b", "c"]}  
mock拦截：response: ({ query }) => {console.log(query.selectProps)}
结果： 线上环境："c"          开发环境："a", "b", "c"

尝试使用response中opt的url进行解析获取完整数组参数，发现在线上环境中url是undefined
备注：axios配置使用qs.stringify(params, { indices: false })

**Comment by webzihe** [comment]
你好请问一下你是怎么在线上环境使用的  我配置
prodEnabled: true, // 生产环境是否开启
enable: true, // 开启或关闭mock
但是线上环境还是没有mock请求

**Comment by Lin-Van** [comment]
// mock支持
    viteMockServe({
      mockPath: "mock",
      localEnabled: command === "serve",
      prodEnabled: command !== "serve" && prodMock,
      injectCode: `
          import { setupProdMockServer } from './mockProdServer';
          setupProdMockServer();
        `,
      logger: false
    }),

**Comment by Lin-Van** [comment]
> 你好请问一下你是怎么在线上环境使用的 我配置 prodEnabled: true, // 生产环境是否开启 enable: true, // 开启或关闭mock 但是线上环境还是没有mock请求

```javascript
// mock支持
    viteMockServe({
      mockPath: "mock",
      localEnabled: command === "serve",
      prodEnabled: command !== "serve" && prodMock,
      injectCode: `
          import { setupProdMockServer } from './mockProdServer';
          setupProdMockServer();
        `,
      logger: false
    }),
```
