### ISSUE TITLE
    "importsNotUsedAsValues": "error"不兼容

### ISSUE THREAD

**Issue by rjl-cli** [vbenjs/vite-plugin-mock#95]
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["types/env.d.ts", "src/**/*", "src/**/*.vue", "src/**/*.tsx"],
  "compilerOptions": {
    "ignoreDeprecations": "5.0",
    "allowSyntheticDefaultImports": false,
    "module": "ESNext",
    "types": ["@types/node", "vite/client"],
    "typeRoots": ["./node_modules/@types/", "./types/"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },

  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
中@vue/tsconfig/tsconfig.web.json 有     "importsNotUsedAsValues": "error" 和这和插件不兼容
启动会
![image](https://user-images.githubusercontent.com/111716113/230250558-c72c1cf2-7e2b-4be3-a736-0eff64e334a9.png)

**Comment by anncwb** [comment]
这个属性在typescipt5已经被标记为弃用了，可以尝试覆盖关闭
