### ISSUE TITLE
运行yarn dev报错 vite版本4.2.1 ReferenceError: require is not defined

### ISSUE THREAD

**Issue by L-T-G** [vbenjs/vite-plugin-mock#97]
![image](https://user-images.githubusercontent.com/50793941/232447687-4deb41a5-ee9f-4c77-9ff6-72d3addfdb4b.png)

**Comment by badlym** [comment]
我的也是，同问

**Comment by wjw020206** [comment]
巧了，我这边vite版本4.2.2运行也遇到这个问题

**Comment by wjw020206** [comment]
似乎和 vite 的版本没有关系，把 vite-plugin-mock 降到 2.9.8 就可以正常运行了

**Comment by lincenying** [comment]
"type": "module" 下, 不存在require, 导致报错误

**Comment by jinzhirong** [comment]
我今天也是这个问题，我是3.0.0，明天试试把type去掉看行不行

**Comment by lincenying** [comment]
> 我今天也是这个问题，我是3.0.0，明天试试把type去掉看行不行

想用3.0 可以先用 `@lincy/vite-plugin-mock`, 然后等作者更新吧

**Comment by mazhenxiao** [comment]
![image](https://user-images.githubusercontent.com/6904018/236980815-a74d4df6-089d-4bf5-bfa7-9ac2f1115f96.png)
相同的问题，因为采用的是commandjs语法，在vite的ems语法中不支持，尝试解决采用@rollup/plugin-commonjs组件但是依然无效，应该只是针对开发中混合方式引入的cmd语法模块才有用，在当前编译环境下并不支持。

**Comment by vimianma** [comment]
我也遇到这个问题，首先降了版本发现还是存在require的问题，后来把node_module中vite-plugin-mock的index.mjs删掉后就正常了，mock功能也能正常使用！

**Comment by CodingAndSleeping** [comment]
我也遇到了这个错误，我把package.json里的 type:module 删掉了就好了

**Comment by lbw611** [comment]
3.0.0的版本，vite4.2.3我也遇到了这个错误。降了版本到2.9.8可以运行了

**Comment by abc-0886kAX-code** [comment]
vite-plugin-mock@2.9.8解决了  谢谢鸭
![Snipaste_2023-05-26_15-01-26](https://github.com/vbenjs/vite-plugin-mock/assets/86451477/1cf3c2fe-5a52-4fae-ba68-1245128b6d43)

**Comment by ibzero** [comment]
找到 `/dist/index.mjs` ，注释 `cleanRequireCache(opt);`

**Comment by 776488326** [comment]
点击提示的位置在if条件内容改为 if (typeof require === "undefined" || !require.cache)
<img width="807" alt="image" src="https://github.com/vbenjs/vite-plugin-mock/assets/40347810/5c18f29b-09af-48c8-b428-05e0ca743765">

**Comment by catyumouse** [comment]
@lincenying package.json 去掉了type:module可以运行了

**Comment by songyipan** [comment]
> 点击提示的位置在if条件内容改为 if (typeof require === "undefined" || !require.cache) <img alt="image" width="807" src="https://user-images.githubusercontent.com/40347810/242598557-5c18f29b-09af-48c8-b428-05e0ca743765.png">

牛逼

**Comment by zmtyc** [comment]
https://github.com/vbenjs/vite-plugin-mock/issues/109#issuecomment-1712430646

**Comment by liaohaoxiang** [comment]
> 点击提示的位置在if条件内容改为 if (typeof require === "undefined" || !require.cache) <img alt="image" width="807" src="https://user-images.githubusercontent.com/40347810/242598557-5c18f29b-09af-48c8-b428-05e0ca743765.png">

去掉"type": "module"会损失esm， 用这个方法可以使用

**Comment by ryuushihou** [comment]
> #109 package.json 去掉`"type": "module",`

这个办法解决了 原因是什么呀
